dist: xenial
language: python
python:
  - 2.7
  - 3.6
  - 3.7
cache: pip
install:
  - pip install tox-travis pytest-cov coveralls
script: tox
after_success: coveralls
notifications:
  email:
    on_success: never
    on_failure: always
